module Web.Detail.View exposing (view)

import Html exposing (..)
import Html.Attributes as Attr exposing (..)


view =
    div [ class "sc-bZQynM cGXOSN" ]
        [ section [ class "sc-kpOJdX hIjqJZ" ]
            [ header [ class "sc-gqjmRU fuOOfM" ]
                [ div [ class "sc-VigVT ksrMsQ" ]
                    [ a [ href "/" ]
                        [ text "← Back to list" ]
                    ]
                , h2 [ class "sc-jTzLTM JLGmz" ]
                    [ text "The Empire Strikes Back" ]
                , p [ class "sc-fjdhpX dGakJQ" ]
                    [ text "Director : Irvin Kershner" ]
                , p [ class "sc-fjdhpX dGakJQ" ]
                    [ text "Producer : Gary Kurtz, Rick McCallum" ]
                ]
            , div [ class "sc-jzJRlG xsNml" ]
                [ h4 [ class "sc-cSHVUG dolGod" ]
                    [ text "Description" ]
                , p [ class "sc-kAzzGY kAZAcX" ]
                    [ text "It is a dark time for the\nRebellion. Although the Death\nStar has been destroyed,\nImperial troops have driven the\nRebel forces from their hidden\nbase and pursued them across\nthe galaxy.\n\nEvading the dreaded Imperial\nStarfleet, a group of freedom\nfighters led by Luke Skywalker\nhas established a new secret\nbase on the remote ice world\nof Hoth.\n\nThe evil lord Darth Vader,\nobsessed with finding young\nSkywalker, has dispatched\nthousands of remote probes into\nthe far reaches of space...." ]
                ]
            , div [ class "sc-jzJRlG sc-chPdSV dkpFFr" ]
                [ h4 [ class "sc-cSHVUG dolGod" ]
                    [ text "Characters" ]
                , ul [ class "sc-kgoBCf gyvrcq" ]
                    [ li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Luke Skywalker" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "C-3PO" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "R2-D2" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Darth Vader" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Leia Organa" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Obi-Wan Kenobi" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Chewbacca" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Han Solo" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Wedge Antilles" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Yoda" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Palpatine" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Boba Fett" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "IG-88" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Bossk" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Lando Calrissian" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Lobot" ]
                    ]
                ]
            , div [ class "sc-jzJRlG sc-chPdSV dkpFFr" ]
                [ h4 [ class "sc-cSHVUG dolGod" ]
                    [ text "Planets" ]
                , ul [ class "sc-kgoBCf gyvrcq" ]
                    [ li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Hoth" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Dagobah" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Bespin" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Ord Mantell" ]
                    ]
                ]
            , div [ class "sc-jzJRlG sc-chPdSV dkpFFr" ]
                [ h4 [ class "sc-cSHVUG dolGod" ]
                    [ text "Species" ]
                , ul [ class "sc-kgoBCf gyvrcq" ]
                    [ li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Human" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Droid" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Wookie" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Yoda's species" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Trandoshan" ]
                    ]
                ]
            , div [ class "sc-jzJRlG sc-chPdSV dkpFFr" ]
                [ h4 [ class "sc-cSHVUG dolGod" ]
                    [ text "Starships" ]
                , ul [ class "sc-kgoBCf gyvrcq" ]
                    [ li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Star Destroyer" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Millennium Falcon" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Y-wing" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "X-wing" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Executor" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Rebel transport" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Slave 1" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Imperial shuttle" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "EF76 Nebulon-B escort frigate" ]
                    ]
                ]
            , div [ class "sc-jzJRlG sc-chPdSV dkpFFr" ]
                [ h4 [ class "sc-cSHVUG dolGod" ]
                    [ text "Vehicles" ]
                , ul [ class "sc-kgoBCf gyvrcq" ]
                    [ li [ class "sc-kGXeez eDKDkK" ]
                        [ text "TIE/LN starfighter" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Snowspeeder" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "TIE bomber" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "AT-AT" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "AT-ST" ]
                    , li [ class "sc-kGXeez eDKDkK" ]
                        [ text "Storm IV Twin-Pod cloud car" ]
                    ]
                ]
            ]
        ]
